"""create markets table

Revision ID: 4d4427e60319
Revises: 
Create Date: 2026-07-11 15:59:06.242043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4427e60319'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_id', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('sport', sa.String(length=100), nullable=True),
    sa.Column('league', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('liquidity', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_markets_market_id'), 'markets', ['market_id'], unique=True)
    op.create_index(op.f('ix_markets_slug'), 'markets', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_markets_slug'), table_name='markets')
    op.drop_index(op.f('ix_markets_market_id'), table_name='markets')
    op.drop_table('markets')
    # ### end Alembic commands ###
